# This is a basic workflow to help you get started with Actions

name: GH Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      # Runs a set of commands using the runners shell
      - name: Make Pages
        run: |
          npm i
          npx parcel build src/index.html --public-url './'
          rm -rf package-lock.json
          git checkout pages
          mv dist/* .
          rm -rf dist node_modules src package.json .parcel-cache
          ls -al
          git config --global user.name 'adamjc'
          git config --global user.email 'adamjc@users.noreply.github.com'
          git add .
          git commit -m "Updating Pages"
          git push
